// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmvDIa-33jCyA64yPlhi0F3xxHGSfFDtk',
    appId: '1:758746573:web:c3234f6474f999b5e20884',
    messagingSenderId: '758746573',
    projectId: 'sauap-planner-app',
    authDomain: 'sauap-planner-app.firebaseapp.com',
    storageBucket: 'sauap-planner-app.appspot.com',
    measurementId: 'G-ER9XN9JQ5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3J9lTRHSvbjU7te0yOSlLhOIt4UZNHfo',
    appId: '1:758746573:android:74db74dfc594504fe20884',
    messagingSenderId: '758746573',
    projectId: 'sauap-planner-app',
    storageBucket: 'sauap-planner-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOKH9nLf5YoBS1kwfVcdXzPyOgXRPVgM',
    appId: '1:758746573:ios:e81b4ba2705ebd87e20884',
    messagingSenderId: '758746573',
    projectId: 'sauap-planner-app',
    storageBucket: 'sauap-planner-app.appspot.com',
    iosBundleId: 'com.example.sauapPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxOKH9nLf5YoBS1kwfVcdXzPyOgXRPVgM',
    appId: '1:758746573:ios:e81b4ba2705ebd87e20884',
    messagingSenderId: '758746573',
    projectId: 'sauap-planner-app',
    storageBucket: 'sauap-planner-app.appspot.com',
    iosBundleId: 'com.example.sauapPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmvDIa-33jCyA64yPlhi0F3xxHGSfFDtk',
    appId: '1:758746573:web:2c6d91a531b40693e20884',
    messagingSenderId: '758746573',
    projectId: 'sauap-planner-app',
    authDomain: 'sauap-planner-app.firebaseapp.com',
    storageBucket: 'sauap-planner-app.appspot.com',
    measurementId: 'G-DXWNMQDMVB',
  );
}
