// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA03grNFAzQ98zppN4_KE-Q317JlPYqFRo',
    appId: '1:874229837585:web:00827ab13d70fc153de6b0',
    messagingSenderId: '874229837585',
    projectId: 'sauapplannerapp',
    authDomain: 'sauapplannerapp.firebaseapp.com',
    storageBucket: 'sauapplannerapp.appspot.com',
    measurementId: 'G-C67BVCKQ90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvoZKdybczV29exak3InDudeTfqKcUoWA',
    appId: '1:874229837585:android:fb42a436e548d0953de6b0',
    messagingSenderId: '874229837585',
    projectId: 'sauapplannerapp',
    storageBucket: 'sauapplannerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYMUL4wDQHoURNjXBSDJ10pUNcjs4tThk',
    appId: '1:874229837585:ios:54744f1681e406df3de6b0',
    messagingSenderId: '874229837585',
    projectId: 'sauapplannerapp',
    storageBucket: 'sauapplannerapp.appspot.com',
    iosBundleId: 'com.example.sauapPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYMUL4wDQHoURNjXBSDJ10pUNcjs4tThk',
    appId: '1:874229837585:ios:c63e4788e0bd5a9d3de6b0',
    messagingSenderId: '874229837585',
    projectId: 'sauapplannerapp',
    storageBucket: 'sauapplannerapp.appspot.com',
    iosBundleId: 'com.example.sauapPlanner.RunnerTests',
  );
}
